# fly.toml app configuration file generated for hocphi-info-api on 2026-09-06T03:38:20+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hocphi-info-api'
primary_region = 'sin'

[env]
PORT = '8000'
ALLOW_ORIGINS = 'https://hocphi.info,https://www.hocphi.info'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']


[[http_service.checks]]
grace_period = "10s" # generous enough for DB pool warm-up on cold start
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 512
