-- seeds/002_majors — ngành để nạp seeds/*.jsonl (xem docs/plans/2026-09-05-001-
-- ...-plan.md § Phụ lục cho 16 ngành Tuần 2 gốc). +62 ngành (2026-09-05, Tuần 4
-- batch) để nạp hutech.jsonl / ulis.jsonl / dh-hoa-sen.jsonl — xem
-- scripts/seed_majors_mapping.py để biết dòng nào trong file nào map vào đâu.
--
-- `code` = NULL (mã ngành cấp IV chưa xác định cho pilot này — cho phép theo
-- schema §3). `group_code` gán theo nhóm GẦN NGHĨA NHẤT trong 6 nhóm cố định
-- đã seed ở migration 0001 (CNTT/KY_THUAT/KINH_TE/Y_DUOC/LUAT/LOGISTICS) — vài
-- ngành (ngôn ngữ, xã hội học, triết học, báo chí...) không có nhóm khớp thật
-- sự, đây là lựa chọn TẠM, owner nên xem lại nếu sau này thêm nhóm ngành mới.
-- `requires_practice_license` để false cho tất cả kể cả Dược học — chưa gán
-- post_grad_requirements (việc của Tuần 3), tránh vi phạm CHECK
-- ck_majors_practice_profession và bịa practice_profession chưa có nguồn.
--
-- Idempotent qua ON CONFLICT (slug) — partial unique index (xem 001_schools.sql).

INSERT INTO majors (slug, name, code, group_code, standard_years) VALUES
  ('ke-toan',                          'Kế toán',                                  NULL, 'KINH_TE',   4),
  ('thiet-ke-do-hoa',                  'Thiết kế đồ họa',                          NULL, 'KY_THUAT',  4),
  ('duoc-hoc',                         'Dược học',                                 NULL, 'Y_DUOC',    6),
  ('du-lich',                          'Du lịch',                                  NULL, 'KINH_TE',   4),
  ('bao-ho-lao-dong',                  'Bảo hộ lao động',                          NULL, 'KY_THUAT',  4),
  ('xa-hoi-hoc',                       'Xã hội học',                               NULL, 'LUAT',      4),
  ('ngon-ngu-anh',                     'Ngôn ngữ Anh',                             NULL, 'KINH_TE',   4),
  ('ngon-ngu-trung-quoc',              'Ngôn ngữ Trung Quốc',                      NULL, 'KINH_TE',   4),
  ('kinh-doanh-quoc-te',               'Kinh doanh quốc tế',                       NULL, 'KINH_TE',   4),
  ('ky-thuat-dieu-khien-tu-dong-hoa',  'Kỹ thuật điều khiển và tự động hóa',       NULL, 'KY_THUAT',  4),
  ('quan-ly-cong-va-chinh-sach',       'Quản lý công và chính sách',               NULL, 'LUAT',      4),
  ('ky-thuat-phan-mem',                'Kỹ thuật phần mềm',                        NULL, 'CNTT',      4),
  ('quan-tri-khach-san-quoc-te',       'Quản trị khách sạn quốc tế',               NULL, 'KINH_TE',   4),
  ('cong-nghe-thong-tin',              'Công nghệ thông tin',                      NULL, 'CNTT',      4),
  ('triet-hoc',                        'Triết học',                                NULL, 'LUAT',      4),
  ('bao-chi',                          'Báo chí',                                  NULL, 'LUAT',      4),
  -- +62 ngành (2026-09-05) — HUTECH khóa 2026 (56) + ULIS ngôn ngữ (6 riêng,
  -- 2 dùng chung slug ngon-ngu-nhat/ngon-ngu-han với HUTECH).
  ('an-ninh-mang', 'An ninh mạng', NULL, 'CNTT', 4),
  ('an-toan-thong-tin', 'An toàn thông tin', NULL, 'CNTT', 4),
  ('bat-dong-san', 'Bất động sản', NULL, 'KINH_TE', 4),
  ('cong-nghe-dien-anh-truyen-hinh', 'Công nghệ điện ảnh truyền hình', NULL, 'KY_THUAT', 4),
  ('cong-nghe-ky-thuat-o-to', 'Công nghệ kỹ thuật ô tô', NULL, 'KY_THUAT', 4),
  ('cong-nghe-o-to-dien', 'Công nghệ ô tô điện', NULL, 'KY_THUAT', 4),
  ('cong-nghe-o-to-thong-minh', 'Công nghệ ô tô thông minh', NULL, 'KY_THUAT', 4),
  ('cong-nghe-sinh-hoc', 'Công nghệ sinh học', NULL, 'KY_THUAT', 4),
  ('cong-nghe-tai-chinh', 'Công nghệ tài chính', NULL, 'KINH_TE', 4),
  ('cong-nghe-tham-my', 'Công nghệ thẩm mỹ', NULL, 'KY_THUAT', 4),
  ('cong-nghe-thuc-pham', 'Công nghệ thực phẩm', NULL, 'KY_THUAT', 4),
  ('dieu-duong', 'Điều dưỡng', NULL, 'Y_DUOC', 4),
  ('digital-art', 'Digital Art', NULL, 'KY_THUAT', 4),
  ('digital-marketing', 'Digital Marketing', NULL, 'KINH_TE', 4),
  ('he-thong-thong-tin-quan-ly', 'Hệ thống thông tin quản lý', NULL, 'CNTT', 4),
  ('khoa-hoc-du-lieu', 'Khoa học dữ liệu', NULL, 'CNTT', 4),
  ('khoa-hoc-may-tinh', 'Khoa học máy tính', NULL, 'CNTT', 4),
  ('kien-truc', 'Kiến trúc', NULL, 'KY_THUAT', 5),
  ('kinh-doanh-thuong-mai', 'Kinh doanh thương mại', NULL, 'KINH_TE', 4),
  ('kinh-te-so', 'Kinh tế số', NULL, 'KINH_TE', 4),
  ('ky-thuat-co-dien-tu', 'Kỹ thuật cơ điện tử', NULL, 'KY_THUAT', 4),
  ('ky-thuat-co-khi', 'Kỹ thuật cơ khí', NULL, 'KY_THUAT', 4),
  ('ky-thuat-dien', 'Kỹ thuật điện', NULL, 'KY_THUAT', 4),
  ('ky-thuat-dien-tu-vien-thong', 'Kỹ thuật điện tử - viễn thông', NULL, 'KY_THUAT', 4),
  ('ky-thuat-may-tinh', 'Kỹ thuật máy tính', NULL, 'CNTT', 4),
  ('ky-thuat-xay-dung', 'Kỹ thuật xây dựng', NULL, 'KY_THUAT', 4),
  ('ky-thuat-xet-nghiem-y-hoc', 'Kỹ thuật xét nghiệm y học', NULL, 'Y_DUOC', 4),
  ('logistics-va-quan-ly-chuoi-cung-ung', 'Logistics và quản lý chuỗi cung ứng', NULL, 'LOGISTICS', 4),
  ('luat', 'Luật', NULL, 'LUAT', 4),
  ('luat-kinh-te', 'Luật kinh tế', NULL, 'LUAT', 4),
  ('marketing', 'Marketing', NULL, 'KINH_TE', 4),
  ('marketing-va-truyen-thong-sang-tao', 'Marketing và truyền thông sáng tạo', NULL, 'KINH_TE', 4),
  ('ngon-ngu-a-rap', 'Ngôn ngữ Ả Rập', NULL, 'KINH_TE', 4),
  ('ngon-ngu-duc', 'Ngôn ngữ Đức', NULL, 'KINH_TE', 4),
  ('ngon-ngu-han', 'Ngôn ngữ Hàn', NULL, 'KINH_TE', 4),
  ('ngon-ngu-nga', 'Ngôn ngữ Nga', NULL, 'KINH_TE', 4),
  ('ngon-ngu-nhat', 'Ngôn ngữ Nhật', NULL, 'KINH_TE', 4),
  ('ngon-ngu-phap', 'Ngôn ngữ Pháp', NULL, 'KINH_TE', 4),
  ('quan-he-cong-chung', 'Quan hệ công chúng', NULL, 'LUAT', 4),
  ('quan-ly-the-duc-the-thao', 'Quản lý thể dục thể thao', NULL, 'KINH_TE', 4),
  ('quan-ly-xay-dung', 'Quản lý xây dựng', NULL, 'KY_THUAT', 4),
  ('quan-tri-dich-vu-du-lich-va-lu-hanh', 'Quản trị dịch vụ du lịch và lữ hành', NULL, 'KINH_TE', 4),
  ('quan-tri-khach-san', 'Quản trị khách sạn', NULL, 'KINH_TE', 4),
  ('quan-tri-kinh-doanh', 'Quản trị kinh doanh', NULL, 'KINH_TE', 4),
  ('quan-tri-nha-hang-va-dich-vu-an-uong', 'Quản trị nhà hàng và dịch vụ ăn uống', NULL, 'KINH_TE', 4),
  ('quan-tri-nhan-luc', 'Quản trị nhân lực', NULL, 'KINH_TE', 4),
  ('quan-tri-su-kien', 'Quản trị sự kiện', NULL, 'KINH_TE', 4),
  ('quan-tri-va-phap-che-doanh-nghiep', 'Quản trị và pháp chế doanh nghiệp', NULL, 'KINH_TE', 4),
  ('robot-tri-tue-nhan-tao', 'Robot & trí tuệ nhân tạo', NULL, 'KY_THUAT', 4),
  ('tai-chinh-ngan-hang', 'Tài chính - Ngân hàng', NULL, 'KINH_TE', 4),
  ('tam-ly-hoc', 'Tâm lý học', NULL, 'LUAT', 4),
  ('thanh-nhac', 'Thanh nhạc', NULL, 'KY_THUAT', 4),
  ('thiet-ke-noi-that', 'Thiết kế nội thất', NULL, 'KY_THUAT', 4),
  ('thiet-ke-thoi-trang', 'Thiết kế thời trang', NULL, 'KY_THUAT', 4),
  ('thu-y', 'Thú y', NULL, 'Y_DUOC', 5),
  ('thu-y-cong-nghe-so', 'Thú y công nghệ số', NULL, 'Y_DUOC', 5),
  ('thuong-mai-dien-tu', 'Thương mại điện tử', NULL, 'KINH_TE', 4),
  ('tieng-viet-va-van-hoa-viet-nam', 'Tiếng Việt và văn hóa Việt Nam', NULL, 'KINH_TE', 4),
  ('tri-tue-nhan-tao', 'Trí tuệ nhân tạo', NULL, 'CNTT', 4),
  ('truyen-thong-da-phuong-tien', 'Truyền thông đa phương tiện', NULL, 'KY_THUAT', 4),
  ('van-hoa-va-truyen-thong-xuyen-quoc-gia', 'Văn hóa và truyền thông xuyên quốc gia', NULL, 'KINH_TE', 4),
  ('y-khoa', 'Y khoa', NULL, 'Y_DUOC', 6),
  -- +29 ngành (2026-09-05) — IU (7 riêng) + HCMUS (22 riêng), 4 ngành dùng
  -- chung slug giữa 2 truong (thong-ke, toan-ung-dung, khoa-hoc-du-lieu,
  -- ky-thuat-dien-tu-vien-thong — 2 slug sau da co san).
  ('kinh-te', 'Kinh tế', NULL, 'KINH_TE', 4),
  ('ky-thuat-he-thong-cong-nghiep', 'Kỹ thuật Hệ thống Công nghiệp', NULL, 'KY_THUAT', 4),
  ('hoa-hoc-hoa-sinh', 'Hóa học (Hóa sinh)', NULL, 'KY_THUAT', 4),
  ('ky-thuat-hoa-hoc', 'Kỹ thuật Hóa học', NULL, 'KY_THUAT', 4),
  ('ky-thuat-y-sinh', 'Kỹ thuật Y sinh', NULL, 'KY_THUAT', 4),
  ('ky-thuat-khong-gian', 'Kỹ thuật Không gian', NULL, 'KY_THUAT', 4),
  ('thong-ke', 'Thống kê', NULL, 'CNTT', 4),
  ('toan-ung-dung', 'Toán ứng dụng', NULL, 'CNTT', 4),
  ('sinh-hoc', 'Sinh học', NULL, 'KY_THUAT', 4),
  ('vat-ly-hoc', 'Vật lý học', NULL, 'KY_THUAT', 4),
  ('cong-nghe-vat-ly-dien-tu-va-tin-hoc', 'Công nghệ vật lý điện tử và tin học', NULL, 'KY_THUAT', 4),
  ('hoa-hoc', 'Hoá học', NULL, 'KY_THUAT', 4),
  ('khoa-hoc-vat-lieu', 'Khoa học vật liệu', NULL, 'KY_THUAT', 4),
  ('dia-chat-hoc', 'Địa chất học', NULL, 'KY_THUAT', 4),
  ('kinh-te-dat-dai', 'Kinh tế đất đai', NULL, 'KINH_TE', 4),
  ('hai-duong-hoc', 'Hải dương học', NULL, 'KY_THUAT', 4),
  ('khoa-hoc-moi-truong', 'Khoa học môi trường', NULL, 'KY_THUAT', 4),
  ('toan-hoc', 'Toán học', NULL, 'CNTT', 4),
  ('toan-tin', 'Toán tin', NULL, 'CNTT', 4),
  ('nhom-nganh-cong-nghe-thong-tin', 'Nhóm ngành Công nghệ thông tin', NULL, 'CNTT', 4),
  ('cong-nghe-vat-lieu', 'Công nghệ Vật liệu', NULL, 'KY_THUAT', 4),
  ('cong-nghe-ky-thuat-moi-truong', 'Công nghệ Kỹ thuật Môi trường', NULL, 'KY_THUAT', 4),
  ('ky-thuat-hat-nhan', 'Kỹ thuật hạt nhân', NULL, 'KY_THUAT', 4),
  ('vat-ly-y-khoa', 'Vật lý Y Khoa', NULL, 'Y_DUOC', 4),
  ('ky-thuat-dia-chat', 'Kỹ thuật địa chất', NULL, 'KY_THUAT', 4),
  ('quan-ly-tai-nguyen-va-moi-truong', 'Quản lý tài nguyên và Môi trường', NULL, 'KY_THUAT', 4),
  ('cong-nghe-ban-dan', 'Công nghệ bán dẫn', NULL, 'CNTT', 4),
  ('thiet-ke-vi-mach', 'Thiết kế vi mạch', NULL, 'CNTT', 4),
  ('cong-nghe-giao-duc', 'Công nghệ giáo dục', NULL, 'LUAT', 4),
  -- +2 ngành (2026-09-06) — để nạp ftu.jsonl / hcmute.jsonl (Tuần 4 batch bổ
  -- sung). Chỉ 4 dòng trong 2 file đó map được vào 1 ngành cụ thể (phần lớn là
  -- tên hệ / khối ngành → major_slug = null). Xem scripts/seed_majors_mapping.py.
  ('kinh-te-doi-ngoai', 'Kinh tế đối ngoại', NULL, 'KINH_TE', 4),
  ('cong-nghe-truyen-thong', 'Công nghệ truyền thông', NULL, 'KY_THUAT', 4),
  -- +13 ngành (2026-09-06, đợt 2) — để nạp ump.jsonl (12 ngành Y-Dược cụ thể,
  -- bảng học phí dự kiến trong đề án tuyển sinh 1608/TTTS-ĐHYD) + ou-tphcm.jsonl
  -- (1 ngành: cong-nghe-ky-thuat-cong-trinh-xay-dung, ngành nêu tên đầu của một
  -- nhóm). tmu.jsonl KHÔNG có ngành nào — 4 dòng đều là tên hệ đào tạo.
  -- Xem scripts/seed_majors_mapping.py.
  ('y-hoc-du-phong',                'Y học dự phòng',                       NULL, 'Y_DUOC',   6),
  ('y-hoc-co-truyen',              'Y học cổ truyền',                      NULL, 'Y_DUOC',   6),
  ('hoa-duoc',                      'Hóa dược',                             NULL, 'Y_DUOC',   5),
  ('ho-sinh',                       'Hộ sinh',                              NULL, 'Y_DUOC',   4),
  ('dinh-duong',                    'Dinh dưỡng',                           NULL, 'Y_DUOC',   4),
  ('rang-ham-mat',                  'Răng - Hàm - Mặt',                     NULL, 'Y_DUOC',   6),
  ('ky-thuat-phuc-hinh-rang',       'Kỹ thuật phục hình răng',              NULL, 'Y_DUOC',   4),
  ('ky-thuat-hinh-anh-y-hoc',       'Kỹ thuật hình ảnh y học',              NULL, 'Y_DUOC',   4),
  ('ky-thuat-phuc-hoi-chuc-nang',   'Kỹ thuật phục hồi chức năng',          NULL, 'Y_DUOC',   4),
  ('y-te-cong-cong',                'Y tế công cộng',                       NULL, 'Y_DUOC',   4),
  ('cong-tac-xa-hoi',               'Công tác xã hội',                      NULL, 'LUAT',     4),
  ('cong-nghe-duoc-pham',           'Công nghệ dược phẩm',                  NULL, 'Y_DUOC',   4),
  ('cong-nghe-ky-thuat-cong-trinh-xay-dung', 'Công nghệ kỹ thuật công trình xây dựng', NULL, 'KY_THUAT', 4)
ON CONFLICT (slug) WHERE deleted_at IS NULL DO NOTHING;
